### ISSUE TITLE
Non se poden marcan atributos post como requeridos

### ISSUE THREAD

**Issue by alambike** [prefapp/catro-eixos-swagger#4]
Este tipo de atributo nunca se acepta a pesar de enviar correctamente o parámetros a través do swagger-client

```yaml
/users:
    post:
      tags:
      - "Users"
      description: "Register a new user"
      operationId: "users_create"
      parameters: 
      - name: "user"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/User"

```

Swagger-client integrado:

```js
    prepare.cliente()
      .then((cliente) => {
        cliente.procesarPost("Users", "users_create", {
          post: {
            uuid: 'test-uuid',
            plan_slug: 'full-hd'
          }
        })
      })
```

O
```js
    prepare.cliente()
      .then((cliente) => {
        cliente.procesarPost("Users", "users_create", {
          post: {
            user: {
              uuid: 'test-uuid',
              plan_slug: 'full-hd'
            }
          }
        })
      })
```

Produce:
  1) Users Se agrega un usuario:
    **Error: Required parameter user is not provided**

**Comment by frmadem** [comment]
El primer ejemplo y el segundo son diferentes. En el primero no se pasa user, en el segundo sí. Especifica más el tema porque no veo el error. @alambike

**Comment by alambike** [comment]
Son 2 ejemplos que cascan, tal como funciona ahora mismo o cliente. De todas formas ahora xa non é necesario, xa que tirando do swagger-client xa funciona correctamente o paso de parametros por body
