### ISSUE TITLE
Novo metodo 'asignar' para productos swagger

### ISSUE THREAD

**Issue by alambike** [prefapp/catro-eixos-swagger#6]
Que permita asignar directamente un obxeto ao producto, de forma que non haxa que ir clave a clave para setealo, sin que esto puentee as validacións.

```js
asignar(obj){
    Object.assign(this,obj);
}
```

Polo menos para os de tipo objecto e array.

**Comment by frmadem** [comment]
Agregado en este [commit](https://github.com/prefapp/catro-eixos-swagger/commit/9d8832aff6d623a3a3c9b9f463181a6e0cc8ea06)

**Comment by alambike** [comment]
Co `Object.assign` tamén chuta, estouno usando en STR para facer a asignacion
