### ISSUE TITLE
Soporte para o resto de verbos HTTP:  PATCH , PUT  e DELETE

### ISSUE THREAD

**Issue by alambike** [prefapp/catro-eixos-swagger#7]
Actualmente o cliente so soporta GET e POST, parece

probar co swagger-client orixinal a ver

**Comment by frmadem** [comment]
No tengo muy claro el problema. Es el cliente quien tramita y el middleware de swagger el que recibe. El soporte para verbos REST es algo en lo que catro-eixos-swagger no se mete. 

Podemos crear una aplicación para testeo con un servidor y un cliente a ver e introducirlos en los tests.

**Comment by alambike** [comment]
ok
