### ISSUE TITLE
Refactorizar procesarPost para que tire polos metodos normales do swagger-client

### ISSUE THREAD

**Issue by alambike** [prefapp/catro-eixos-swagger#8]
Co método procesar é suficiente, pero no codigo que siga usando procesarPost non vai a funcionar correctamente porque non se está pasando ben os parámetros de body.

Para correxilo podemos refactorizar procesarPost para que use procesar, pero antes mergeo os parámetros mandados no hash de post co resto de parámetros

**Comment by frmadem** [comment]
Corregido en [issue](https://github.com/prefapp/catro-eixos-swagger/commit/8ae295f5d0406d624e135cd484b7d67817a3ba48)
